# Generated by Django 5.0.2 on 2024-02-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authCode',
            field=models.IntegerField(default=990809),
        ),
    ]
